# Generated by Django 3.2.9 on 2021-11-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('serving_size', models.CharField(max_length=30)),
                ('calorie_kJ', models.CharField(max_length=10)),
                ('calorie_kcal', models.CharField(max_length=10)),
                ('carbohydrate', models.CharField(max_length=10)),
                ('sugar', models.CharField(max_length=10)),
                ('protein', models.CharField(max_length=10)),
                ('fat', models.CharField(max_length=10)),
                ('fat_2', models.CharField(max_length=10)),
                ('fat_3', models.CharField(max_length=10)),
                ('fat_4', models.CharField(max_length=10, null=True)),
                ('fat_5', models.CharField(max_length=10, null=True)),
                ('dietary_fiber', models.CharField(max_length=10, null=True)),
                ('potassium', models.CharField(max_length=10, null=True)),
                ('cholesterol', models.CharField(max_length=10)),
                ('salt', models.CharField(max_length=10, null=True)),
                ('voice1', models.CharField(max_length=255)),
                ('voice2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Yolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('class_name', models.CharField(max_length=50)),
            ],
        ),
    ]
