# Generated by Django 3.2.9 on 2021-11-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='sal',
            new_name='salt',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='info',
            new_name='voice1',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='voice2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
